import type { ActionCard } from '../types';

export const ACTIONS: ActionCard[] = [
  { id: 'ac-001', name: '気合のかけ声', effect: { kind: 'stat_mod', stat: 'atk', amount: 2, duration: 'next_battle' } },
  { id: 'ac-002', name: '構え直し', effect: { kind: 'stat_mod', stat: 'def', amount: 2, duration: 'next_battle' } },
  { id: 'ac-003', name: '助走', effect: { kind: 'stat_mod', stat: 'spd', amount: 2, duration: 'next_battle' } },
  { id: 'ac-004', name: '体力回復', effect: { kind: 'stat_mod', stat: 'hp', amount: 3, duration: 'next_battle' } },
  { id: 'ac-005', name: '修練', effect: { kind: 'stat_mod', stat: 'atk', amount: 2, duration: 'permanent' } },
  { id: 'ac-006', name: '鍛錬', effect: { kind: 'stat_mod', stat: 'def', amount: 2, duration: 'permanent' } },
  { id: 'ac-007', name: '走り込み', effect: { kind: 'stat_mod', stat: 'spd', amount: 2, duration: 'permanent' } },
  { id: 'ac-008', name: '増強', effect: { kind: 'stat_mod', stat: 'hp', amount: 3, duration: 'permanent' } },
  { id: 'ac-009', name: '墓場あさり', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-010', name: '探索', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-011', name: '深呼吸', effect: { kind: 'stat_mod', stat: 'hp', amount: 4, duration: 'next_battle' } },
  { id: 'ac-012', name: '突撃姿勢', effect: { kind: 'stat_mod', stat: 'atk', amount: 3, duration: 'next_battle' } },
  { id: 'ac-013', name: '防御陣形', effect: { kind: 'stat_mod', stat: 'def', amount: 3, duration: 'next_battle' } },
  { id: 'ac-014', name: '加速装置', effect: { kind: 'stat_mod', stat: 'spd', amount: 3, duration: 'next_battle' } },
  { id: 'ac-015', name: 'スキル整理', effect: { kind: 'discard_random_active' } },
  { id: 'ac-016', name: '掘り出し物', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-017', name: '修行', effect: { kind: 'stat_mod', stat: 'atk', amount: 2, duration: 'permanent' } },
  { id: 'ac-018', name: '盾磨き', effect: { kind: 'stat_mod', stat: 'def', amount: 2, duration: 'permanent' } },
  { id: 'ac-019', name: '俊敏訓練', effect: { kind: 'stat_mod', stat: 'spd', amount: 2, duration: 'permanent' } },
  { id: 'ac-020', name: '体力増強', effect: { kind: 'stat_mod', stat: 'hp', amount: 3, duration: 'permanent' } },
  { id: 'ac-021', name: '記憶の欠片', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-022', name: '師匠の教え', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-023', name: '攻撃の極意', effect: { kind: 'stat_mod', stat: 'atk', amount: 4, duration: 'next_battle' } },
  { id: 'ac-024', name: '防御の極意', effect: { kind: 'stat_mod', stat: 'def', amount: 4, duration: 'next_battle' } },
  { id: 'ac-025', name: '迅雷の歩み', effect: { kind: 'stat_mod', stat: 'spd', amount: 4, duration: 'next_battle' } },
  { id: 'ac-026', name: '生命の泉', effect: { kind: 'stat_mod', stat: 'hp', amount: 5, duration: 'next_battle' } },
  { id: 'ac-027', name: '禁書の解読', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-028', name: '亡霊召喚', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-029', name: '基礎訓練', effect: { kind: 'stat_mod', stat: 'atk', amount: 2, duration: 'permanent' } },
  { id: 'ac-030', name: '修復作業', effect: { kind: 'stat_mod', stat: 'def', amount: 2, duration: 'permanent' } },
  { id: 'ac-031', name: '瞬発訓練', effect: { kind: 'stat_mod', stat: 'spd', amount: 2, duration: 'permanent' } },
  { id: 'ac-032', name: '生命操作', effect: { kind: 'stat_mod', stat: 'hp', amount: 3, duration: 'permanent' } },
  { id: 'ac-033', name: '気合一撃', effect: { kind: 'stat_mod', stat: 'atk', amount: 2, duration: 'next_battle' } },
  { id: 'ac-034', name: '盾の構え', effect: { kind: 'stat_mod', stat: 'def', amount: 2, duration: 'next_battle' } },
  { id: 'ac-035', name: '駆け足', effect: { kind: 'stat_mod', stat: 'spd', amount: 2, duration: 'next_battle' } },
  { id: 'ac-036', name: '小休憩', effect: { kind: 'stat_mod', stat: 'hp', amount: 3, duration: 'next_battle' } },
  { id: 'ac-037', name: '剣術修行', effect: { kind: 'stat_mod', stat: 'atk', amount: 2, duration: 'permanent' } },
  { id: 'ac-038', name: '体作り', effect: { kind: 'stat_mod', stat: 'def', amount: 2, duration: 'permanent' } },
  { id: 'ac-039', name: '足腰鍛え', effect: { kind: 'stat_mod', stat: 'spd', amount: 2, duration: 'permanent' } },
  { id: 'ac-040', name: 'スタミナ強化', effect: { kind: 'stat_mod', stat: 'hp', amount: 3, duration: 'permanent' } },
  { id: 'ac-041', name: '探求', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-042', name: '発掘', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-043', name: '亡骸あさり', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-044', name: '記憶の蘇り', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-045', name: '禁断修行', effect: { kind: 'stat_mod', stat: 'atk', amount: 3, duration: 'permanent' } },
  { id: 'ac-046', name: '鋼鉄修練', effect: { kind: 'stat_mod', stat: 'def', amount: 3, duration: 'permanent' } },
  { id: 'ac-047', name: '高速移動', effect: { kind: 'stat_mod', stat: 'spd', amount: 3, duration: 'permanent' } },
  { id: 'ac-048', name: '不要技処分', effect: { kind: 'discard_random_active' } },
  { id: 'ac-049', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-050', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-051', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-052', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-053', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-054', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-055', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-056', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-057', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
  { id: 'ac-058', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1, duration: 'permanent' } },
];
