import type { ActionCard } from '../types';
import rawOverrides from './actions.overrides.json';

export const ACTIONS: ActionCard[] = [
  { id: 'ac-001', name: '気合のかけ声', effect: { kind: 'stat_mod', stat: 'atk', amount: 2 } },
  { id: 'ac-002', name: '構え直し', effect: { kind: 'stat_mod', stat: 'def', amount: 2 } },
  { id: 'ac-003', name: '助走', effect: { kind: 'stat_mod', stat: 'spd', amount: 2 } },
  { id: 'ac-004', name: '体力回復', effect: { kind: 'stat_mod', stat: 'hp', amount: 3 } },
  { id: 'ac-005', name: '修練', effect: { kind: 'stat_mod', stat: 'atk', amount: 2 } },
  { id: 'ac-006', name: '鍛錬', effect: { kind: 'stat_mod', stat: 'def', amount: 2 } },
  { id: 'ac-007', name: '走り込み', effect: { kind: 'stat_mod', stat: 'spd', amount: 2 } },
  { id: 'ac-008', name: '増強', effect: { kind: 'stat_mod', stat: 'hp', amount: 3 } },
  { id: 'ac-009', name: '墓場あさり', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-010', name: '探索', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-011', name: '深呼吸', effect: { kind: 'stat_mod', stat: 'hp', amount: 4 } },
  { id: 'ac-012', name: '突撃姿勢', effect: { kind: 'stat_mod', stat: 'atk', amount: 3 } },
  { id: 'ac-013', name: '防御陣形', effect: { kind: 'stat_mod', stat: 'def', amount: 3 } },
  { id: 'ac-014', name: '加速装置', effect: { kind: 'stat_mod', stat: 'spd', amount: 3 } },
  { id: 'ac-015', name: 'スキル整理', effect: { kind: 'discard_random_active' } },
  { id: 'ac-016', name: '掘り出し物', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-017', name: '修行', effect: { kind: 'stat_mod', stat: 'atk', amount: 2 } },
  { id: 'ac-018', name: '盾磨き', effect: { kind: 'stat_mod', stat: 'def', amount: 2 } },
  { id: 'ac-019', name: '俊敏訓練', effect: { kind: 'stat_mod', stat: 'spd', amount: 2 } },
  { id: 'ac-020', name: '体力増強', effect: { kind: 'stat_mod', stat: 'hp', amount: 3 } },
  { id: 'ac-021', name: '記憶の欠片', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-022', name: '師匠の教え', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-023', name: '攻撃の極意', effect: { kind: 'stat_mod', stat: 'atk', amount: 4 } },
  { id: 'ac-024', name: '防御の極意', effect: { kind: 'stat_mod', stat: 'def', amount: 4 } },
  { id: 'ac-025', name: '迅雷の歩み', effect: { kind: 'stat_mod', stat: 'spd', amount: 4 } },
  { id: 'ac-026', name: '生命の泉', effect: { kind: 'stat_mod', stat: 'hp', amount: 5 } },
  { id: 'ac-027', name: '禁書の解読', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-028', name: '亡霊召喚', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-029', name: '基礎訓練', effect: { kind: 'stat_mod', stat: 'atk', amount: 2 } },
  { id: 'ac-030', name: '修復作業', effect: { kind: 'stat_mod', stat: 'def', amount: 2 } },
  { id: 'ac-031', name: '瞬発訓練', effect: { kind: 'stat_mod', stat: 'spd', amount: 2 } },
  { id: 'ac-032', name: '生命操作', effect: { kind: 'stat_mod', stat: 'hp', amount: 3 } },
  { id: 'ac-033', name: '気合一撃', effect: { kind: 'stat_mod', stat: 'atk', amount: 2 } },
  { id: 'ac-034', name: '盾の構え', effect: { kind: 'stat_mod', stat: 'def', amount: 2 } },
  { id: 'ac-035', name: '駆け足', effect: { kind: 'stat_mod', stat: 'spd', amount: 2 } },
  { id: 'ac-036', name: '小休憩', effect: { kind: 'stat_mod', stat: 'hp', amount: 3 } },
  { id: 'ac-037', name: '剣術修行', effect: { kind: 'stat_mod', stat: 'atk', amount: 2 } },
  { id: 'ac-038', name: '体作り', effect: { kind: 'stat_mod', stat: 'def', amount: 2 } },
  { id: 'ac-039', name: '足腰鍛え', effect: { kind: 'stat_mod', stat: 'spd', amount: 2 } },
  { id: 'ac-040', name: 'スタミナ強化', effect: { kind: 'stat_mod', stat: 'hp', amount: 3 } },
  { id: 'ac-041', name: '探求', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-042', name: '発掘', effect: { kind: 'draw_skill_top' } },
  { id: 'ac-043', name: '亡骸あさり', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-044', name: '記憶の蘇り', effect: { kind: 'recover_skill_from_grave' } },
  { id: 'ac-045', name: '禁断修行', effect: { kind: 'stat_mod', stat: 'atk', amount: 3 } },
  { id: 'ac-046', name: '鋼鉄修練', effect: { kind: 'stat_mod', stat: 'def', amount: 3 } },
  { id: 'ac-047', name: '高速移動', effect: { kind: 'stat_mod', stat: 'spd', amount: 3 } },
  { id: 'ac-048', name: '不要技処分', effect: { kind: 'discard_random_active' } },
  { id: 'ac-049', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-050', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-051', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-052', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-053', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-054', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-055', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-056', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-057', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-058', name: '汎用訓練', effect: { kind: 'stat_mod_choice', amount: 1 } },
  { id: 'ac-059', name: 'スキル順入れ替え', effect: { kind: 'swap_actives' } },
  { id: 'ac-060', name: 'バグ発生', effect: { kind: 'become_bug' } },
  { id: 'ac-061', name: '解呪', effect: { kind: 'cleanse_sin' } },
  { id: 'ac-062', name: '懺悔', effect: { kind: 'cleanse_sin' } },
  // ── New action cards (ac-063 to ac-082) ─────────────────────────────────
  { id: 'ac-063', name: 'ATK強奪', effect: { kind: 'steal_stat', stat: 'atk', amount: 2 } },
  { id: 'ac-064', name: 'SPD強奪', effect: { kind: 'steal_stat', stat: 'spd', amount: 2 } },
  { id: 'ac-065', name: 'DEF強奪', effect: { kind: 'steal_stat', stat: 'def', amount: 2 } },
  { id: 'ac-066', name: 'HP奪取', effect: { kind: 'steal_stat', stat: 'hp', amount: 4 } },
  { id: 'ac-067', name: 'ATK模倣', effect: { kind: 'copy_stat_from_leader', stat: 'atk' } },
  { id: 'ac-068', name: 'SPD模倣', effect: { kind: 'copy_stat_from_leader', stat: 'spd' } },
  { id: 'ac-069', name: 'DEF→ATK変換', effect: { kind: 'trade_stat', from: 'def', to: 'atk', fromAmount: 3, toAmount: 4 } },
  { id: 'ac-070', name: 'ATK→SPD変換', effect: { kind: 'trade_stat', from: 'atk', to: 'spd', fromAmount: 2, toAmount: 3 } },
  { id: 'ac-071', name: 'SPD→ATK変換', effect: { kind: 'trade_stat', from: 'spd', to: 'atk', fromAmount: 3, toAmount: 4 } },
  { id: 'ac-072', name: 'HP→ATK変換', effect: { kind: 'trade_stat', from: 'hp', to: 'atk', fromAmount: 6, toAmount: 4 } },
  { id: 'ac-073', name: 'DEF→HP変換', effect: { kind: 'trade_stat', from: 'def', to: 'hp', fromAmount: 2, toAmount: 5 } },
  { id: 'ac-074', name: 'スキル直結', effect: { kind: 'slot_top_skill' } },
  { id: 'ac-075', name: 'スキル昇格', effect: { kind: 'upgrade_skill' } },
  { id: 'ac-076', name: '技術盗用', effect: { kind: 'copy_skill_from_player' } },
  { id: 'ac-077', name: '体力変換', effect: { kind: 'hp_to_atk', fraction: 0.2 } },
  { id: 'ac-078', name: '全能強化', effect: { kind: 'all_stats_mod', amount: 1 } },
  { id: 'ac-079', name: '超全能強化', effect: { kind: 'all_stats_mod', amount: 2 } },
  { id: 'ac-080', name: '大訓練', effect: { kind: 'stat_mod_choice', amount: 2 } },
  { id: 'ac-081', name: '全能大交換', effect: { kind: 'swap_all_stats' } },
  { id: 'ac-082', name: '時の恩恵', effect: { kind: 'round_scaled_stat_mod', stat: 'atk', perRound: 2 } },
];

type ActionOverride = { description?: string };
const actionOverrides = rawOverrides as Record<string, ActionOverride>;
if (Object.keys(actionOverrides).length > 0) {
  for (const card of ACTIONS) {
    const ov = actionOverrides[card.id];
    if (ov?.description !== undefined) card.description = ov.description;
  }
}
