import type { SkillCard } from '../types';
import rawOverrides from './skills.overrides.json';

/**
 * Skill deck. Distribution roughly N:28 / R:20 / SR:12 / SSR:4 + 6 passive
 * variants. Each card carries a `nameTag` — a short noun the player can use
 * to compose their monster's display name.
 */
export const SKILLS: SkillCard[] = [
  // ─── N (Normal) ────────────────────────────────────────────────────────────
  { id: 'sk-n-001', name: '攻撃', rarity: 'N', active: { effect: { kind: 'attack', mult: 1.0, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-n-009', name: '回復', rarity: 'N', active: { effect: { kind: 'heal', amount: 3 } } },
  { id: 'sk-n-010', name: '小盾', rarity: 'N', active: { effect: { kind: 'shield', amount: 2 } } },
  { id: 'sk-n-011', name: '気合の構え', rarity: 'N', active: { effect: { kind: 'buff_self', stat: 'atk', amount: 3, duration: 'once' } } },
  { id: 'sk-n-012', name: '守護の構え', rarity: 'N', active: { effect: { kind: 'buff_self', stat: 'def', amount: 3, duration: 'once' } } },
  { id: 'sk-n-013', name: '威嚇', rarity: 'N', active: { effect: { kind: 'debuff_target', stat: 'atk', amount: 2, duration: 'battle' } } },
  { id: 'sk-n-014', name: '軟化', rarity: 'N', active: { effect: { kind: 'debuff_target', stat: 'def', amount: 2, duration: 'battle' } } },
  { id: 'sk-n-015', name: '鈍化', rarity: 'N', active: { effect: { kind: 'debuff_target', stat: 'spd', amount: 2, duration: 'battle' } } },
  { id: 'sk-n-016', name: '小傷', rarity: 'N', active: { effect: { kind: 'true_damage', amount: 2 } } },
  { id: 'sk-n-020', name: '硬化', rarity: 'N', active: { effect: { kind: 'buff_self', stat: 'def', amount: 2, duration: 'battle' } } },
  { id: 'sk-n-021', name: '集中', rarity: 'N', active: { effect: { kind: 'buff_self', stat: 'atk', amount: 2, duration: 'battle' } } },
  { id: 'sk-n-022', name: '加速', rarity: 'N', active: { effect: { kind: 'buff_self', stat: 'spd', amount: 2, duration: 'battle' } } },
  { id: 'sk-n-028', name: '影刺し', rarity: 'R', nameTag: 'シャドウ', active: { effect: { kind: 'true_damage', amount: 4 } } },

  // ─── R (Rare) ──────────────────────────────────────────────────────────────
  { id: 'sk-r-001', name: '強攻撃', rarity: 'R', nameTag: 'パワー', active: { effect: { kind: 'attack', mult: 1.3, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-r-002', name: '貫通刺突', rarity: 'SR', nameTag: 'ピアサー', active: { effect: { kind: 'true_damage', amount: 6 } } },
  { id: 'sk-r-004', name: 'いばらの盾', rarity: 'R', nameTag: 'ソーン', active: { effect: { kind: 'reflect_shield', amount: 3 } } },
  { id: 'sk-r-054', name: 'オーラ', rarity: 'R', nameTag: 'オーラ', active: { effect: { kind: 'threshold_shield', threshold: 3 } } },
  { id: 'sk-r-005', name: '気力解放', rarity: 'R', nameTag: 'レイジ', active: { effect: { kind: 'buff_self', stat: 'atk', amount: 6, duration: 'once' } } },
  { id: 'sk-r-006', name: '岩石防御', rarity: 'R', nameTag: 'ロックアーマー', active: { effect: { kind: 'buff_self', stat: 'def', amount: 6, duration: 'once' } } },
  { id: 'sk-r-007', name: '光速', rarity: 'R', nameTag: 'ブースター', active: { effect: { kind: 'buff_self', stat: 'spd', amount: 4, duration: 'battle' } } },
  { id: 'sk-r-008', name: '威圧', rarity: 'R', nameTag: 'タイラント', active: { effect: { kind: 'debuff_target', stat: 'atk', amount: 4, duration: 'battle' } } },
  { id: 'sk-r-009', name: '剥離', rarity: 'R', nameTag: 'ブレイカー', active: { effect: { kind: 'debuff_target', stat: 'def', amount: 4, duration: 'battle' } } },
  { id: 'sk-r-010', name: '束縛', rarity: 'R', nameTag: 'フリーザー', active: { effect: { kind: 'debuff_target', stat: 'spd', amount: 4, duration: 'battle' } } },
  { id: 'sk-r-029', name: '闘気', rarity: 'R', nameTag: 'フォース', active: { effect: { kind: 'buff_self', stat: 'atk', amount: 4, duration: 'battle' } } },
  { id: 'sk-r-012', name: '見切り', rarity: 'SR', nameTag: 'ウィザード', active: { effect: { kind: 'nullify_next' } } },
  { id: 'sk-r-015', name: '癒しの風', rarity: 'R', nameTag: 'ヒーリング', active: { effect: { kind: 'heal', amount: 5 } } },
  { id: 'sk-r-016', name: '中盾', rarity: 'R', nameTag: 'シルバー', active: { effect: { kind: 'shield', amount: 4 } } },
  { id: 'sk-r-055', name: '盾割り', rarity: 'R', nameTag: 'シールドブレイカー', active: { effect: { kind: 'shield_break_attack', useStat: 'atk', multNoShield: 1.0, multShield: 2.0, attackKind: 'strike' } } },
  // ─── 七つの大罪 (Sin cards) ──────────────────────────────────────────────
  { id: 'sk-r-056', name: '虚栄の罪', rarity: 'N', nameTag: 'プライド', tag: 'sin', active: { effect: { kind: 'grant_target_shield', amount: 1 } } },
  { id: 'sk-r-057', name: '嫉妬の罪', rarity: 'N', nameTag: 'エンヴィ', tag: 'sin', active: { effect: { kind: 'buff_target', stat: 'atk', amount: 2, duration: 'battle' } } },
  { id: 'sk-r-058', name: '怠惰の罪', rarity: 'N', nameTag: 'スロウス', tag: 'sin', active: { effect: { kind: 'self_nullify_next' } } },
  { id: 'sk-r-059', name: '憤怒の罪', rarity: 'N', nameTag: 'ラース', tag: 'sin', active: { effect: { kind: 'self_damage_max_fraction', fraction: 0.3 } } },
  { id: 'sk-r-060', name: '強欲の罪', rarity: 'N', nameTag: 'グリード', tag: 'sin', active: { effect: { kind: 'buff_self', stat: 'def', amount: -2, duration: 'battle' } } },
  { id: 'sk-r-061', name: '暴食の罪', rarity: 'N', nameTag: 'グラトニー', tag: 'sin', active: { effect: { kind: 'buff_self', stat: 'spd', amount: -4, duration: 'battle' } } },
  { id: 'sk-r-062', name: '色欲の罪', rarity: 'N', nameTag: 'ラスト', tag: 'sin', active: { effect: { kind: 'heal_target_max_fraction', fraction: 0.2 } } },
  { id: 'sk-r-017', name: '要塞', rarity: 'R', nameTag: 'バランス', active: { effect: { kind: 'buff_self', stat: 'def', amount: 4, duration: 'battle' } } },
  { id: 'sk-r-018', name: '速攻', rarity: 'R', nameTag: 'ラピッド', active: { effect: { kind: 'attack', mult: 1.1, useStat: 'spd', attackKind: 'passthrough' } } },
  { id: 'sk-r-019', name: 'シールドバッシュ', rarity: 'R', nameTag: 'バッシュ', active: { effect: { kind: 'attack', mult: 1.2, useStat: 'def', attackKind: 'strike' } } },
  { id: 'sk-r-021', name: '生命変換', rarity: 'R', nameTag: 'コンバート', active: { effect: { kind: 'pay_hp_shield', hpCost: 3, shieldAmount: 5 } } },
  { id: 'sk-r-022', name: '取引', rarity: 'R', nameTag: 'トレーダー', active: { effect: { kind: 'pay_hp_debuff_all', hpCost: 4, amount: 1 } } },
  { id: 'sk-r-023', name: '賭け一閃', rarity: 'R', nameTag: 'ギャンブラー', active: { effect: { kind: 'gamble_true_damage', amount: 8, percent: 50 } } },
  { id: 'sk-r-024', name: 'エネルギーチャージ', rarity: 'R', nameTag: 'バッテリー', active: { effect: { kind: 'buff_self_all', amount: 1, duration: 'battle' } } },
  { id: 'sk-r-025', name: 'リフレイン', rarity: 'R', nameTag: 'リフレイン', active: { effect: { kind: 'rewind_skill', rewindBy: 1, selfDamage: 2 } } },
  { id: 'sk-r-026', name: 'デジャヴ・アタック', rarity: 'R', nameTag: 'デジャヴ', active: { effect: { kind: 'deja_vu_attack', mult: 1.0, useStat: 'atk', attackKind: 'passthrough' } } },
  // ─── 相手ステータス参照（カウンターメタ） ──────────────────────────────────
  { id: 'sk-r-063', name: '逆鱗', rarity: 'R', nameTag: 'リバース', active: { effect: { kind: 'target_stat_damage', stat: 'atk', mult: 0.8 } } },
  { id: 'sk-r-064', name: '鎧貫き', rarity: 'R', nameTag: 'アーマーピアサー', active: { effect: { kind: 'target_stat_damage', stat: 'def', mult: 0.8 } } },
  { id: 'sk-r-065', name: '格上狩り', rarity: 'R', nameTag: 'ジャイアントキラー', active: { effect: { kind: 'conditional_attack_if_target_higher', stat: 'atk', multIf: 2.0, multElse: 1.0, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-r-066', name: '守り崩し', rarity: 'R', nameTag: 'ウォールブレイク', active: { effect: { kind: 'conditional_attack_if_target_higher', stat: 'def', multIf: 2.0, multElse: 1.0, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-sr-048', name: '怒りの代償', rarity: 'SR', nameTag: 'リトリビューション', active: { effect: { kind: 'stat_diff_damage', stat: 'atk', mult: 2.0 } } },
  { id: 'sk-sr-049', name: '防壁崩し', rarity: 'SR', nameTag: 'フォートレスブレイク', active: { effect: { kind: 'conditional_attack_if_target_higher', stat: 'def', multIf: 2.5, multElse: 1.0, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-sr-050', name: '反転の刃', rarity: 'SR', nameTag: 'ミラーブレイド', active: { effect: { kind: 'target_higher_stat_attack', mult: 1.0, attackKind: 'sword' } } },
  { id: 'sk-sr-051', name: '天の逆鱗', rarity: 'SR', nameTag: 'ドラゴンレイジ', active: { effect: { kind: 'target_stat_damage', stat: 'atk', mult: 1.3 } } },
  { id: 'sk-sr-052', name: '装甲崩壊', rarity: 'SR', nameTag: 'アーマーブレイク', active: { effect: { kind: 'target_stat_damage', stat: 'def', mult: 1.3 } } },
  { id: 'sk-sr-053', name: '大物狩り', rarity: 'SR', nameTag: 'タイタンキラー', active: { effect: { kind: 'conditional_attack_if_target_higher', stat: 'atk', multIf: 3.0, multElse: 1.0, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-sr-054', name: '要塞砲', rarity: 'SR', nameTag: 'フォートレス', active: { effect: { kind: 'target_stat_damage', stat: 'def', mult: 0.7 } } },
  { id: 'sk-ssr-021', name: '絶対要塞砲', rarity: 'SSR', nameTag: 'フォートレスキャノン', active: { effect: { kind: 'target_stat_damage', stat: 'def', mult: 1.0 } } },

  // ─── SR (Super Rare) ───────────────────────────────────────────────────────
  { id: 'sk-sr-001', name: '必殺攻撃', rarity: 'SR', nameTag: 'スレイヤー', active: { effect: { kind: 'attack', mult: 1.5, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-sr-003', name: '貫通の理', rarity: 'SSR', nameTag: 'バニッシャー', active: { effect: { kind: 'true_damage', amount: 8 } } },
  { id: 'sk-sr-004', name: '大回復', rarity: 'SR', nameTag: 'セイント', active: { effect: { kind: 'heal', amount: 8 } } },
  { id: 'sk-sr-005', name: '大盾', rarity: 'SR', nameTag: 'ガーディアン', active: { effect: { kind: 'shield', amount: 7 } } },
  { id: 'sk-sr-044', name: '鉄棘の盾', rarity: 'SR', nameTag: 'アイアンソーン', active: { effect: { kind: 'reflect_shield', amount: 5 } } },
  { id: 'sk-sr-046', name: 'ハイ・オーラ', rarity: 'SR', nameTag: 'ハイオーラ', active: { effect: { kind: 'pay_hp_threshold_shield', hpCostFraction: 0.25, threshold: 5 } } },
  { id: 'sk-sr-047', name: '鎧砕き', rarity: 'SR', nameTag: 'アーマークラッシャー', active: { effect: { kind: 'shield_break_attack', useStat: 'atk', multNoShield: 1.2, multShield: 3.0, attackKind: 'strike' } } },
  { id: 'sk-sr-006', name: '剛力の解放', rarity: 'SR', nameTag: 'タイタン', active: { effect: { kind: 'buff_self', stat: 'atk', amount: 6, duration: 'battle' } } },
  { id: 'sk-sr-007', name: '鋼鉄の肉体', rarity: 'SR', nameTag: 'スチール', active: { effect: { kind: 'buff_self', stat: 'def', amount: 6, duration: 'battle' } } },
  { id: 'sk-sr-008', name: '神速の波動', rarity: 'SR', nameTag: 'ゴッドスピード', active: { effect: { kind: 'buff_self', stat: 'spd', amount: 6, duration: 'battle' } } },
  { id: 'sk-sr-009', name: '威圧の咆哮', rarity: 'SR', nameTag: 'デモン', active: { effect: { kind: 'debuff_target', stat: 'atk', amount: 6, duration: 'battle' } } },
  { id: 'sk-sr-010', name: '一挙集中', rarity: 'SR', nameTag: 'オーバードライブ', active: { effect: { kind: 'next_amp', mult: 2.0 } } },
  { id: 'sk-sr-012', name: '装甲の粉砕', rarity: 'SR', nameTag: 'クラッシャー', active: { effect: { kind: 'debuff_target', stat: 'def', amount: 6, duration: 'battle' } } },
  { id: 'sk-sr-018', name: '時空の束縛', rarity: 'SR', nameTag: 'タイムストップ', active: { effect: { kind: 'debuff_target', stat: 'spd', amount: 6, duration: 'battle' } } },
  { id: 'sk-sr-020', name: '豪鬼咆哮', rarity: 'SR', nameTag: 'オーバーロード', active: { effect: { kind: 'buff_self', stat: 'atk', amount: 9, duration: 'once' } } },
  { id: 'sk-sr-035', name: '絶対防壁', rarity: 'SR', nameTag: 'バリア', active: { effect: { kind: 'buff_self', stat: 'def', amount: 9, duration: 'once' } } },
  { id: 'sk-sr-013', name: '一時停止', rarity: 'SR', nameTag: 'ポーズ', active: { effect: { kind: 'pause_opponent' } } },
  { id: 'sk-sr-014', name: 'ハリケーン', rarity: 'SR', nameTag: 'ストーム', active: { effect: { kind: 'shuffle_opponent_actives' } } },
  { id: 'sk-sr-015', name: '二重起動', rarity: 'SR', nameTag: 'ダブル', active: { effect: { kind: 'next_multi_attack', extraCount: 1, failurePenalty: 2 } } },
  { id: 'sk-sr-016', name: '百花繚乱', rarity: 'SSR', nameTag: 'バリスタ', active: { effect: { kind: 'multi_hit_attack', mult: 0.7, useStat: 'atk', hitCount: 4, attackKind: 'passthrough' } } },
  { id: 'sk-sr-017', name: 'フラッシュバック', rarity: 'SR', nameTag: 'フラッシュバック', active: { effect: { kind: 'rewind_skill', rewindBy: 2, selfDamage: 4 } } },

  // ─── SSR ───────────────────────────────────────────────────────────────────
  { id: 'sk-ssr-001', name: '究極奥義', rarity: 'SSR', nameTag: 'ドラゴン', active: { effect: { kind: 'attack', mult: 3.0, useStat: 'atk', attackKind: 'passthrough' } } },
  { id: 'sk-ssr-003', name: '聖なる盾', rarity: 'SSR', nameTag: 'セレスチャル', active: { effect: { kind: 'shield', amount: 12 } } },
  { id: 'sk-ssr-018', name: '返り血の盾', rarity: 'SSR', nameTag: 'ブラッドソーン', active: { effect: { kind: 'reflect_shield', amount: 10 } } },
  { id: 'sk-ssr-019', name: 'マキシム・オーラ', rarity: 'SSR', nameTag: 'マキシム', active: { effect: { kind: 'pay_hp_threshold_shield', hpCostFraction: 0.5, threshold: 7 } } },
  { id: 'sk-ssr-020', name: '絶壁砕き', rarity: 'SSR', nameTag: 'ウォールブレイカー', active: { effect: { kind: 'shield_break_attack', useStat: 'atk', multNoShield: 1.5, multShield: 4.0, attackKind: 'strike' } } },
  { id: 'sk-ssr-004', name: '集中砲火', rarity: 'SSR', nameTag: 'クロノス', active: { effect: { kind: 'next_amp', mult: 3.0 } } },
  { id: 'sk-ssr-005', name: '三重起動', rarity: 'SSR', nameTag: 'トリプル', active: { effect: { kind: 'next_multi_attack', extraCount: 2, failurePenalty: 6 } } },
  { id: 'sk-ssr-006', name: '時を巻き戻す', rarity: 'SSR', nameTag: 'リワインド', active: { effect: { kind: 'heal_max_fraction', denominator: 2 } } },
  { id: 'sk-ssr-007', name: 'エターナル', rarity: 'SSR', nameTag: 'エターナル', active: { effect: { kind: 'rewind_skill', rewindBy: 3, selfDamage: 7 } } },

  // ─── Passive skill cards ───────────────────────────────────────────────────
  {
    id: 'sk-rp-001',
    name: '先制の構え (passive)',
    rarity: 'R',
    nameTag: 'リーダー',
    isPassive: true,
    passive: { trigger: { kind: 'first_attack' }, effect: { kind: 'first_attack_amp', amount: 1 } },
  },
  {
    id: 'sk-rp-002',
    name: '再生 (passive)',
    rarity: 'R',
    nameTag: 'リジェネ',
    isPassive: true,
    passive: { trigger: { kind: 'on_own_turn_start' }, effect: { kind: 'turn_start_heal_even', amount: 2 } },
  },
  {
    id: 'sk-srp-001',
    name: '鋼の体 (passive)',
    rarity: 'SR',
    nameTag: 'タンク',
    isPassive: true,
    passive: { trigger: { kind: 'on_take_damage' }, effect: { kind: 'damage_reduction', amount: 1 } },
  },
  {
    id: 'sk-srp-002',
    name: '見切りの構え (passive)',
    rarity: 'SR',
    nameTag: 'ファントム',
    isPassive: true,
    passive: { trigger: { kind: 'on_take_damage' }, effect: { kind: 'damage_negate_chance', oneIn: 6 } },
  },
  {
    id: 'sk-srp-003',
    name: '食いしばり (passive)',
    rarity: 'SR',
    nameTag: 'サバイバー',
    isPassive: true,
    passive: { trigger: { kind: 'on_take_damage' }, effect: { kind: 'endure_fatal' } },
  },
  {
    id: 'sk-ssrp-001',
    name: '影討ち (passive)',
    rarity: 'SSR',
    nameTag: 'アサシン',
    isPassive: true,
    passive: {
      trigger: { kind: 'first_attack' },
      effect: { kind: 'first_attack_def_div', denominator: 2 },
    },
  },
  {
    id: 'sk-ssrp-002',
    name: '時の積層 (passive)',
    rarity: 'SSR',
    nameTag: 'タイムロード',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'atk_per_active', amount: 2, every: 2 },
    },
  },
  {
    id: 'sk-srp-005',
    name: '逆転する世界 (passive)',
    rarity: 'SR',
    nameTag: 'リバース',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'reverse_actives_both' },
    },
  },
  {
    id: 'sk-rp-003',
    name: '逆境 (passive)',
    rarity: 'R',
    nameTag: 'アンダードッグ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'low_hp_damage_reduction', amount: 2 },
    },
  },
  {
    id: 'sk-rp-004',
    name: '呪いの鎖 (passive)',
    rarity: 'R',
    nameTag: 'カース',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_active_used' },
      effect: { kind: 'self_decay', hp: 1, atk: 0, def: 0, spd: 0 },
    },
  },
  {
    id: 'sk-srp-006',
    name: 'クリティカル (passive)',
    rarity: 'SR',
    nameTag: 'スナイパー',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'crit_chance', percent: 20, mult: 2 },
    },
  },
  {
    id: 'sk-srp-007',
    name: '影武者 (passive)',
    rarity: 'SR',
    nameTag: 'シャドウ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'absorb_first_hit' },
    },
  },
  {
    id: 'sk-srp-008',
    name: '同調 (passive)',
    rarity: 'SR',
    nameTag: 'シンクロ',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'equalize_spd' },
    },
  },
  // ── R actives (new) ─────────────────────────────────────────────────────
  {
    id: 'sk-r-029',
    name: '吸命術',
    rarity: 'R',
    nameTag: 'ドレイン',
    active: { effect: { kind: 'drain_hp', amount: 1 } },
  },
  {
    id: 'sk-r-030',
    name: '力奪い',
    rarity: 'R',
    nameTag: 'スナッチ',
    active: { effect: { kind: 'steal_stat', stat: 'atk', amount: 2 } },
  },
  {
    id: 'sk-r-031',
    name: '全力弱体',
    rarity: 'R',
    nameTag: 'デビリテイト',
    active: { effect: { kind: 'debuff_all', amount: 1 } },
  },
  {
    id: 'sk-r-032',
    name: '連撃',
    rarity: 'R',
    nameTag: 'クロー',
    active: { effect: { kind: 'multi_hit_attack', mult: 0.9, useStat: 'atk', hitCount: 2, attackKind: 'passthrough' } },
  },
  {
    id: 'sk-r-035',
    name: '陽炎',
    rarity: 'R',
    nameTag: 'ミラージュ',
    active: { effect: { kind: 'gamble_true_damage', amount: 8, percent: 60 } },
  },
  {
    id: 'sk-r-036',
    name: '血の盾',
    rarity: 'R',
    nameTag: 'ブラッド',
    active: { effect: { kind: 'pay_hp_shield', hpCost: 4, shieldAmount: 7 } },
  },
  // ── SR actives (new) ────────────────────────────────────────────────────
  {
    id: 'sk-sr-018',
    name: '盾砕き',
    rarity: 'SR',
    nameTag: 'シールドブレイカー',
    active: { effect: { kind: 'shield_bash' } },
  },
  {
    id: 'sk-sr-019',
    name: '浄化',
    rarity: 'SR',
    nameTag: 'クレンズ',
    active: { effect: { kind: 'dispel' } },
  },
  {
    id: 'sk-sr-021',
    name: '吸命波',
    rarity: 'SR',
    nameTag: 'ライフドレイン',
    active: { effect: { kind: 'drain_hp', amount: 3 } },
  },
  {
    id: 'sk-sr-022',
    name: '鎧剥ぎ',
    rarity: 'SR',
    nameTag: 'アーマーブレイク',
    active: { effect: { kind: 'steal_stat', stat: 'def', amount: 3 } },
  },
  {
    id: 'sk-sr-023',
    name: '全弱体改',
    rarity: 'SR',
    nameTag: 'ヘクス',
    active: { effect: { kind: 'debuff_all', amount: 2 } },
  },
  {
    id: 'sk-sr-024',
    name: 'HP転換',
    rarity: 'SR',
    nameTag: 'スワップ',
    active: { effect: { kind: 'swap_hp' } },
  },
  {
    id: 'sk-sr-025',
    name: '神速斬',
    rarity: 'SR',
    nameTag: 'ソニック',
    active: { effect: { kind: 'attack', mult: 1.3, useStat: 'spd', attackKind: 'sword' } },
  },
  {
    id: 'sk-sr-026',
    name: '覚醒',
    rarity: 'SR',
    nameTag: 'アウェイクン',
    active: { effect: { kind: 'buff_self_all', amount: 3, duration: 'battle' } },
  },
  {
    id: 'sk-sr-027',
    name: '霊脈',
    rarity: 'SR',
    nameTag: 'スピリット',
    active: { effect: { kind: 'heal_max_fraction', denominator: 2 } },
  },
  // ── SSR actives (new) ───────────────────────────────────────────────────
  {
    id: 'sk-ssr-008',
    name: '命懸け',
    rarity: 'SR',
    nameTag: 'サクリファイス',
    active: { effect: { kind: 'sacrifice_attack', hpRatio: 0.5 } },
  },
  {
    id: 'sk-ssr-009',
    name: '完全回復',
    rarity: 'SSR',
    nameTag: 'リバイブ',
    active: { effect: { kind: 'heal_max_fraction', denominator: 1 } },
  },
  {
    id: 'sk-ssr-011',
    name: '完全吸命',
    rarity: 'SSR',
    nameTag: 'ソウルイーター',
    active: { effect: { kind: 'drain_hp', amount: 5 } },
  },
  {
    id: 'sk-ssr-012',
    name: '極魂の一撃',
    rarity: 'SSR',
    nameTag: 'ソウル',
    active: { effect: { kind: 'sacrifice_attack', hpRatio: 0.8 } },
  },
  // ── R passives (new) ────────────────────────────────────────────────────
  {
    id: 'sk-rp-005',
    name: '生命力 (passive)',
    rarity: 'R',
    nameTag: 'バイタル',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'stat_mod', stat: 'hp', amount: 4 },
    },
  },
  {
    id: 'sk-rp-006',
    name: '連撃の才 (passive)',
    rarity: 'R',
    nameTag: 'コンボ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'atk_per_active', amount: 2, every: 2 },
    },
  },
  // ── SR passives (new) ───────────────────────────────────────────────────
  {
    id: 'sk-srp-010',
    name: '閃光回避 (passive)',
    rarity: 'SR',
    nameTag: 'イリュージョン',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'dodge_bonus', percent: 15 },
    },
  },
  // ── SSR passive (new) ───────────────────────────────────────────────────
  {
    id: 'sk-ssrp-003',
    name: '不死の意志 (passive)',
    rarity: 'SSR',
    nameTag: 'ネクロ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'endure_fatal', reviveDenominator: 3 },
    },
  },
  // ── R actives (batch 3) ─────────────────────────────────────────────────
  {
    id: 'sk-r-039',
    name: '奈落の呪い',
    rarity: 'R',
    nameTag: 'グラインダー',
    active: { effect: { kind: 'percent_max_hp_true', percent: 15 } },
  },
  {
    id: 'sk-r-040',
    name: '浄化呪',
    rarity: 'R',
    nameTag: 'ピュリファイ',
    active: { effect: { kind: 'cleanse_self' } },
  },
  {
    id: 'sk-r-041',
    name: '体強化',
    rarity: 'R',
    nameTag: 'リフォーム',
    active: { effect: { kind: 'swap_atk_def' } },
  },
  {
    id: 'sk-r-042',
    name: '集中連撃',
    rarity: 'SR',
    nameTag: 'ラピッド',
    active: { effect: { kind: 'multi_hit_attack', mult: 0.8, useStat: 'atk', hitCount: 3, attackKind: 'strike' } },
  },
  {
    id: 'sk-r-043',
    name: '反魂盾',
    rarity: 'R',
    nameTag: 'リフレクト',
    active: { effect: { kind: 'share_damage_next', percent: 50 } },
  },
  {
    id: 'sk-r-044',
    name: '怒火',
    rarity: 'R',
    nameTag: 'フューリー',
    active: { effect: { kind: 'hp_to_atk', divisor: 3 } },
  },
  {
    id: 'sk-r-045',
    name: '闇打ち',
    rarity: 'R',
    nameTag: 'シャドウ',
    active: { effect: { kind: 'true_damage', amount: 5 } },
  },
  {
    id: 'sk-r-046',
    name: '大気合',
    rarity: 'R',
    nameTag: 'ヒロイック',
    active: { effect: { kind: 'buff_self_all', amount: 2, duration: 'once' } },
  },
  {
    id: 'sk-r-048',
    name: '盾割り',
    rarity: 'R',
    nameTag: 'シールドブレイク',
    active: { effect: { kind: 'break_shield' } },
  },
  // ── SR actives (batch 3) ────────────────────────────────────────────────
  {
    id: 'sk-sr-028',
    name: '死刑宣告',
    rarity: 'SR',
    nameTag: 'エクスキューショナー',
    active: { effect: { kind: 'execute', threshold: 6 } },
  },
  {
    id: 'sk-sr-029',
    name: '命削りの呪縛',
    rarity: 'SR',
    nameTag: 'エロード',
    active: { effect: { kind: 'percent_max_hp_true', percent: 25 } },
  },
  {
    id: 'sk-sr-030',
    name: '鏡盾',
    rarity: 'SR',
    nameTag: 'ミラー',
    active: { effect: { kind: 'share_damage_next', percent: 75 } },
  },
  {
    id: 'sk-sr-031',
    name: 'ガードバースト',
    rarity: 'SR',
    nameTag: 'バースト',
    active: { effect: { kind: 'attack', mult: 1.4, useStat: 'def', attackKind: 'strike' } },
  },
  {
    id: 'sk-sr-033',
    name: '鎧変換',
    rarity: 'SR',
    nameTag: 'メタモル',
    active: { effect: { kind: 'swap_atk_def' } },
  },
  {
    id: 'sk-sr-034',
    name: '怒りの覚醒',
    rarity: 'SR',
    nameTag: 'バーサーク',
    active: { effect: { kind: 'hp_to_atk', divisor: 2 } },
  },
  // ── SSR actives (batch 3) ───────────────────────────────────────────────
  {
    id: 'sk-ssr-013',
    name: '終焉宣告',
    rarity: 'SSR',
    nameTag: 'ジ・エンド',
    active: { effect: { kind: 'execute', threshold: 10 } },
  },
  {
    id: 'sk-ssr-014',
    name: '神槍',
    rarity: 'SSR',
    nameTag: 'ロンギヌス',
    active: { effect: { kind: 'attack', mult: 4.0, useStat: 'atk', attackKind: 'sword' } },
  },
  {
    id: 'sk-ssr-015',
    name: '魂喰い',
    rarity: 'SSR',
    nameTag: 'ジャッジメント',
    active: { effect: { kind: 'percent_max_hp_true', percent: 40 } },
  },
  {
    id: 'sk-ssr-016',
    name: '完全反射',
    rarity: 'SSR',
    nameTag: 'パーフェクトミラー',
    active: { effect: { kind: 'share_damage_next', percent: 100 } },
  },
  // ── R passives (batch 3) ────────────────────────────────────────────────
  {
    id: 'sk-rp-007',
    name: 'ダメージキャップ (passive)',
    rarity: 'R',
    nameTag: 'リミッター',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'damage_cap', maxPerHit: 6 },
    },
  },
  {
    id: 'sk-rp-008',
    name: '弱者狩り (passive)',
    rarity: 'R',
    nameTag: 'ハンター',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'bonus_vs_low_hp', amount: 3 },
    },
  },
  // ── SR passives (batch 3) ───────────────────────────────────────────────
  {
    id: 'sk-srp-011',
    name: '麻痺の毒 (passive)',
    rarity: 'SR',
    nameTag: 'パラライズ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'paralyze_chance', percent: 15 },
    },
  },
  {
    id: 'sk-srp-012',
    name: '完全防御 (passive)',
    rarity: 'SR',
    nameTag: 'インビンシブル',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'damage_cap', maxPerHit: 3 },
    },
  },
  // ── batch 4: misc thematic cards ────────────────────────────────────────
  {
    id: 'sk-r-049',
    name: '捨て身攻撃',
    rarity: 'R',
    nameTag: 'リックレス',
    active: { effect: { kind: 'reckless_attack', mult: 2.0, useStat: 'atk', attackKind: 'strike' } },
  },
  {
    id: 'sk-rp-010',
    name: '慎重派 (passive)',
    rarity: 'R',
    nameTag: 'プルーデント',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'first_received_damage_div', denominator: 2 },
    },
  },
  {
    id: 'sk-sr-036',
    name: 'ものまね',
    rarity: 'SR',
    nameTag: 'コピーキャット',
    active: { effect: { kind: 'mimic_last' } },
  },
  {
    id: 'sk-r-050',
    name: 'シールドバッシュ',
    rarity: 'R',
    nameTag: 'バッシュ',
    active: { effect: { kind: 'def_attack', flat: 2, attackKind: 'strike' } },
  },
  {
    id: 'sk-r-051',
    name: 'ハエたたき',
    rarity: 'R',
    nameTag: 'スワッター',
    active: { effect: { kind: 'swat_attack', mult: 1.0, useStat: 'atk', attackKind: 'strike' } },
  },
  // ── batch 5: late-game / control / counter ──────────────────────────────
  {
    id: 'sk-sr-037',
    name: 'とどめの一撃',
    rarity: 'SR',
    nameTag: 'フィニッシャー',
    active: { effect: { kind: 'coup_de_grace', threshold: 10, amount: 99, attackKind: 'passthrough' } },
  },
  {
    id: 'sk-rp-011',
    name: 'ダンスステップ (passive)',
    rarity: 'R',
    nameTag: 'ダンサー',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'dodge_bonus', percent: 10 },
    },
  },
  {
    id: 'sk-sr-038',
    name: '影縫い',
    rarity: 'SR',
    nameTag: 'シャドウバインド',
    active: { effect: { kind: 'pin_attack', mult: 1.0, useStat: 'atk', flat: -1, attackKind: 'sword' } },
  },
  {
    id: 'sk-r-052',
    name: '魔神斬り',
    rarity: 'R',
    nameTag: 'デモンスラッシュ',
    active: { effect: { kind: 'risky_attack', mult: 2.0, useStat: 'atk', missPercent: 65, attackKind: 'sword' } },
  },
  {
    id: 'sk-sr-039',
    name: 'カウンター',
    rarity: 'SR',
    nameTag: 'カウンター',
    active: { effect: { kind: 'counter_strike', mult: 2.0, attackKind: 'passthrough' } },
  },
  {
    id: 'sk-sr-040',
    name: '諸行無常の刃',
    rarity: 'SR',
    nameTag: 'ヴァニッシュ',
    active: { effect: { kind: 'attack_then_dispel', mult: 1.0, useStat: 'atk', flat: -2, attackKind: 'sword' } },
  },
  {
    id: 'sk-sr-041',
    name: '明鏡止水の刃',
    rarity: 'SR',
    nameTag: 'クリアマインド',
    active: { effect: { kind: 'attack_then_cleanse', mult: 1.0, useStat: 'atk', flat: -2, attackKind: 'sword' } },
  },
  // ── batch 6: append-struggle pair ───────────────────────────────────────
  {
    id: 'sk-sr-042',
    name: '最後の抵抗',
    rarity: 'SR',
    nameTag: 'ラストスタンド',
    active: { effect: { kind: 'append_struggle', target: 'self', count: 3 } },
  },
  {
    id: 'sk-sr-043',
    name: '君臨',
    rarity: 'SR',
    nameTag: 'ドミネーター',
    active: { effect: { kind: 'append_struggle', target: 'opponent', count: 3 } },
  },
  // ── 30 new passives ─────────────────────────────────────────────────────
  // R passives
  {
    id: 'sk-rp-012',
    name: '消耗 (passive)',
    rarity: 'R',
    nameTag: 'デクライン',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_active_used' },
      effect: { kind: 'decay_atk_per_active', amount: 1 },
    },
  },
  {
    id: 'sk-rp-013',
    name: '盾形成 (passive)',
    rarity: 'R',
    nameTag: 'シールドフォーム',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_active_used' },
      effect: { kind: 'shield_on_active', amount: 1 },
    },
  },
  {
    id: 'sk-rp-014',
    name: '余剰回復 (passive)',
    rarity: 'R',
    nameTag: 'リジェネ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_active_used' },
      effect: { kind: 'heal_on_active', amount: 1 },
    },
  },
  {
    id: 'sk-rp-015',
    name: '末期の輝き (passive)',
    rarity: 'R',
    nameTag: 'テイル',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'tail_fury', amount: 4, threshold: 2 },
    },
  },
  {
    id: 'sk-rp-016',
    name: '蝕む炎 (passive)',
    rarity: 'R',
    nameTag: 'スコーチ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_turn_start' },
      effect: { kind: 'slow_burn', amount: 1 },
    },
  },
  {
    id: 'sk-rp-017',
    name: '逆鱗 (passive)',
    rarity: 'R',
    nameTag: 'リベンジ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'revenge_burst', amount: 4 },
    },
  },
  {
    id: 'sk-rp-018',
    name: '反撃の舞 (passive)',
    rarity: 'R',
    nameTag: 'カウンタダンス',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'dodge_counter', amount: 2 },
    },
  },
  {
    id: 'sk-rp-019',
    name: '棘の盾 (passive)',
    rarity: 'R',
    nameTag: 'ソーンズ',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'shield_thorns', amount: 2 },
    },
  },
  {
    id: 'sk-rp-020',
    name: '機会主義 (passive)',
    rarity: 'R',
    nameTag: 'オポチュニスト',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'opportunist', amount: 2 },
    },
  },
  {
    id: 'sk-rp-021',
    name: '鏡像 (passive)',
    rarity: 'R',
    nameTag: 'ミラー',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'mirror_stats' },
    },
  },
  {
    id: 'sk-rp-022',
    name: '攻防転換 (passive)',
    rarity: 'R',
    nameTag: 'リバース',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'stat_swap_battle_start' },
    },
  },
  {
    id: 'sk-rp-024',
    name: '闘気 (passive)',
    rarity: 'R',
    nameTag: 'ファイター',
    isPassive: true,
    passive: {
      trigger: { kind: 'first_attack' },
      effect: { kind: 'first_attack_damage_mult', mult: 1.5 },
    },
  },
  {
    id: 'sk-rp-023',
    name: '盾再生 (passive)',
    rarity: 'R',
    nameTag: 'リジェンシールド',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_turn_start' },
      effect: { kind: 'regen_shield', amount: 2 },
    },
  },
  // SR passives
  {
    id: 'sk-srp-013',
    name: '衝撃緩衝 (passive)',
    rarity: 'SR',
    nameTag: 'バッファー',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'damage_to_shield', percent: 50 },
    },
  },
  {
    id: 'sk-srp-014',
    name: 'セカンドウィンド (passive)',
    rarity: 'SR',
    nameTag: 'セカンド',
    isPassive: true,
    passive: {
      trigger: { kind: 'first_attack' },
      effect: { kind: 'second_wind', amount: 4 },
    },
  },
  {
    id: 'sk-srp-015',
    name: '反転の構え (passive)',
    rarity: 'SR',
    nameTag: 'インバート',
    isPassive: true,
    passive: {
      trigger: { kind: 'first_attack' },
      effect: { kind: 'swap_atk_def_after_first_attack' },
    },
  },
  {
    id: 'sk-srp-016',
    name: '初撃強奪 (passive)',
    rarity: 'SR',
    nameTag: 'スティール',
    isPassive: true,
    passive: {
      trigger: { kind: 'first_attack' },
      effect: { kind: 'first_strike_steal_atk', amount: 2 },
    },
  },
  {
    id: 'sk-srp-017',
    name: '拍子の達人 (passive)',
    rarity: 'SR',
    nameTag: 'リズム',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'odd_turn_atk_bonus', amount: 3 },
    },
  },
  {
    id: 'sk-srp-018',
    name: '連鎖の流れ (passive)',
    rarity: 'SR',
    nameTag: 'チェイン',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'chain_damage_bonus', amount: 1 },
    },
  },
  {
    id: 'sk-srp-019',
    name: '成長の祝福 (passive)',
    rarity: 'SR',
    nameTag: 'グロウス',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_own_turn_start' },
      effect: { kind: 'growth_heal', amount: 1 },
    },
  },
  {
    id: 'sk-srp-020',
    name: '弱肉強食 (passive)',
    rarity: 'SR',
    nameTag: 'プレデター',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'predator_buff', amount: 3 },
    },
  },
  {
    id: 'sk-srp-021',
    name: '防壁意志 (passive)',
    rarity: 'SR',
    nameTag: 'ガードオブウィル',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'opp_crit_block' },
    },
  },
  {
    id: 'sk-srp-022',
    name: 'スロースターター (passive)',
    rarity: 'SR',
    nameTag: 'スロー',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'slow_starter', breakpoint: 3, malus: 2, bonus: 4 },
    },
  },
  {
    id: 'sk-srp-023',
    name: '二重盾 (passive)',
    rarity: 'SR',
    nameTag: 'ダブルシールド',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'double_shield' },
    },
  },
  {
    id: 'sk-srp-024',
    name: '魔法封じ (passive)',
    rarity: 'SR',
    nameTag: 'マジックシール',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'selective_immune', attackKind: 'magic' },
    },
  },
  // SSR passives
  {
    id: 'sk-ssrp-004',
    name: '鋼鉄の鎧 (passive)',
    rarity: 'SSR',
    nameTag: 'スチールアーマー',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'attack_kind_resist', attackKind: 'strike', amount: 4 },
    },
  },
  {
    id: 'sk-ssrp-005',
    name: '断末魔 (passive)',
    rarity: 'SSR',
    nameTag: 'デスラトル',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'last_breath', amount: 12 },
    },
  },
  {
    id: 'sk-ssrp-006',
    name: '神域の幼生 (passive)',
    rarity: 'SSR',
    nameTag: 'インバル',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'immortal_first_phase', until: 2 },
    },
  },
  {
    id: 'sk-ssrp-007',
    name: '輪廻 (passive)',
    rarity: 'SSR',
    nameTag: 'リバース',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_take_damage' },
      effect: { kind: 'rebirth' },
    },
  },
  {
    id: 'sk-ssrp-008',
    name: '時の神 (passive)',
    rarity: 'SSR',
    nameTag: 'クロノス',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'chronos', allBonus: 4, hpDrain: 1 },
    },
  },
  {
    id: 'sk-ssrp-009',
    name: '最終形態 (passive)',
    rarity: 'SSR',
    nameTag: 'ファイナル',
    isPassive: true,
    passive: {
      trigger: { kind: 'on_deal_damage' },
      effect: { kind: 'final_form', amount: 10 },
    },
  },
  // ── エタニティ三段奥義 ─────────────────────────────────────────────────
  {
    id: 'sk-ssrp-010',
    name: '絶対零度 (passive)',
    rarity: 'SSR',
    nameTag: 'ブリザード',
    isPassive: true,
    passive: {
      trigger: { kind: 'battle_start' },
      effect: { kind: 'absolute_zero' },
    },
  },
  {
    id: 'sk-sr-018',
    name: '理外の咆哮',
    rarity: 'SR',
    nameTag: 'フォース',
    active: { effect: { kind: 'force_amp', mult: 3 } },
  },
  {
    id: 'sk-ssr-008',
    name: '永劫の刃',
    rarity: 'SSR',
    nameTag: 'エタニティ',
    active: { effect: { kind: 'spd_diff_multi_attack', flatAtkMod: -1, useStat: 'atk', attackKind: 'sword' } },
  },
];

type SkillOverride = Partial<Pick<SkillCard, 'name' | 'rarity' | 'nameTag' | 'description'>>;
const overrides = rawOverrides as Record<string, SkillOverride>;

if (Object.keys(overrides).length > 0) {
  for (const card of SKILLS) {
    const ov = overrides[card.id];
    if (!ov) continue;
    if (ov.name !== undefined) card.name = ov.name;
    if (ov.rarity !== undefined) card.rarity = ov.rarity;
    if (ov.nameTag !== undefined) card.nameTag = ov.nameTag;
    if (ov.description !== undefined) card.description = ov.description;
  }
}
